name: duckbuck
description: DuckBuck - AI-powered Walkie-Talkie app with real-time voice communication, AI assistant, and smart proximity sensor features for seamless hands-free conversations.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.5.3
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0 
  image_picker: ^1.1.2
  provider: ^6.1.5
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.7
  slide_to_act: ^2.0.2
  skeletonizer: ^2.0.1
  firebase_analytics: ^11.4.5
  firebase_storage: ^12.4.5
  sqflite: ^2.4.1  
  get_it: ^8.0.3 
  firebase_app_check: ^0.3.2+5
  firebase_messaging: ^15.2.5 
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  crypto: ^3.0.6 
  logger: ^2.5.0
  country_code_picker: ^3.3.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  sms_autofill: ^2.4.1
  dio: ^5.8.0+1
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1 
  async: ^2.11.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1 
  proximity_sensor: ^1.3.8 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Production-ready asset optimization
  assets:
    - assets/ 
    - lib/core/legal/
    
